import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  modal: React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          // fontSans.variable
        )}
      >
        <main className="flex min-h-screen flex-col items-center">
          {/* <div
            className="py-4 w-full flex items-center justify-center bg-background text-white"
          >
            <Link href={'/'}>
              <Button variant={'ghost'}>
                정보 저장소
              </Button>
            </Link>
            <Link href={'/place'}>
              <Button variant={'ghost'}>
                서울 저장소
              </Button>
            </Link>
          </div> */}
          {modal}
          {children}
          <div id="modal-root" />
        </main>
      </body>
    </html>
  );
}
