import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import { cn } from "@/lib/utils";
import { Button } from "@/components/ui/button";
import Link from "next/link";
import { Container } from "@/components/Container";
import FloatingActionButton from "@/components/floatingButton";
import { FilterStoreProvider } from "@/stores/filter-store-provider";

// const fontSans = FontSans({
//   subsets: ["latin"],
//   variable: "--font-sans",
// })
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased",
          // fontSans.variable
        )}
      >
        <FilterStoreProvider>
          <div className="flex min-h-screen flex-col">
            {children}
            <FloatingActionButton />
          </div>
        </FilterStoreProvider>
      </body>
    </html>
  );
}
